### ISSUE TITLE
Missing libs

### ISSUE THREAD

**Issue by Scherady** [Ractiv/touch_plus_source_code#5]
Hi,
I cannot locate the following libraries:
- zlibstatic.lib
- uvc.lib
- curllib.lib
- libeay32MD.lib

1- are they all need?
2- if yes where can I find them?
Thank you

**Comment by sheley1998** [comment]
I'm outside at the moment, will have a look once am home.

**Comment by sheley1998** [comment]
Hi, these libraries should have been removed a while back. Could you check
if you've checked out the latest commit on github? Thanks.

**Comment by Scherady** [comment]
Hi, 

I have downloaded the package from github 2 days ago, I assume it is the latest version. 
Here is the complete list of Additional Dependencies from track_plus Property Pages:

dxguid.lib;ole32.lib;strmiids.lib;uuid.lib;opencv_core249.lib;turbojpeg.lib;opencv_highgui249.lib;opencv_imgproc249.lib;opencv_video249.lib;opencv_flann249.lib;opencv_nonfree249.lib;opencv_features2d249.lib;eSPDI.lib;eSPAEAWBCtrl.lib;zlibstatic.lib;uvc.lib;curllib.lib;libeay32MD.lib

Thanks

**Comment by sheley1998** [comment]
The issue has been fixed, could you download the latest version of the
source code and try again? Thanks!

**Comment by Scherady** [comment]
Hi,
I just downloaded now and compiled the sources files, the problem persists. Here is the list of the additional libs:
dxguid.lib;ole32.lib;strmiids.lib;uuid.lib;zlibstatic.lib;uvc.lib;curllib.lib;libeay32MD.lib;ssleay32MD.lib;opencv_core249.lib;turbojpeg.lib;opencv_highgui249.lib;opencv_imgproc249.lib;opencv_video249.lib;opencv_flann249.lib;opencv_nonfree249.lib;opencv_features2d249.lib;eSPDI.lib;eSPAEAWBCtrl.lib;%(AdditionalDependencies)
Thank you

**Comment by sheley1998** [comment]
Seems like there's something wrong with my gitignore settings, I'll try to get it fixed ASAP. In the meanwhile, could you try removing the additional dependencies that were not included?

**Comment by sheley1998** [comment]
Hello, could you help verify whether the problem has been fixed with the
latest commit? Thanks in advance.

**Comment by Scherady** [comment]
Hello,
I succeeded to compile it; as you recommended I removed those libs then I fixed some additional errors.
Now for my application I need to track the 10 fingers while touching the surface.
How should I proceed? Please advise. 
Thank you.

**Comment by sheley1998** [comment]
Could you describe what your setup looks like? We might have to enable some experimental functions in the source code.

**Comment by Scherady** [comment]
I need to have the coordinates of the 10 fingertips while the fingers are taping the surface simultaneously of individually.

**Comment by sheley1998** [comment]
Hi, are you trying to do this on a laptop or pointed on a different surface?

**Comment by Scherady** [comment]
Preferably on a different surface like a table top.

**Comment by JerryBocciJr** [comment]
Do you mean, like on a virtual (piano) keyboard?

**Comment by Scherady** [comment]
Yes;
what could work for a virtual keyboard would work for my application, even though my application is not based on a keyboard.
